spring:
  profiles:
    active: dev
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

  h2:
    console:
      enabled: ${SPRING_H2_CONSOLE_ENABLED}
      path: ${SPRING_H2_CONSOLE_PATH:/h2-console}

  mail:
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
            scope: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE}
            redirect-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI}
        provider:
          linkedin:
            authorization-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_LINKEDIN_AUTHORIZATION_URI}
            token-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_LINKEDIN_TOKEN_URI}
            user-info-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_LINKEDIN_USER_INFO_URI}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}

app:
  frontend-url: ${APP_FRONTEND_URL}
  oauth2:
    redirect-uri: ${APP_OAUTH2_REDIRECT_URI}

linkedin:
  client-id: ${LINKEDIN_CLIENT_ID}
  client-secret: ${LINKEDIN_CLIENT_SECRET}
  redirect-uri: ${LINKEDIN_REDIRECT_URI}

cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      region: ${CLOUD_AWS_REGION}
    venture:
      images-bucket: ${CLOUD_AWS_VENTURE_IMAGES_BUCKET}

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}