spring:
  application:
    name: CoBrother-Web

  datasource:
    url: jdbc:postgresql://localhost:5432/cobrother
    password: 8431465059
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  mail:
    username: vittalkatwe@gmail.com
    password: rwvo lxcv jljk ldwf
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable:
              true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 4792627824-vdes1hk2badtefmj9k8b4gbrb6pqqc3d.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google

server:
  port: 8080

jwt:
  secret: cBp7/MqB9AzeWa6vlrvaIg8KdVI0rNbwgeXG1scQPI8T0CcC4TXb6VcW3OwH1cgGLOqeE7LZ/l7if1OP3v2usA==
  expiration: 36000000
  refresh:
    expiration: 2592000000

app:
  frontend-url: http://localhost:3000
  oauth2:
    redirect-uri: http://localhost:3000/auth/callback

linkedin:
  client-id: 77kepiwbqxdlhh
  client-secret: WPL_AP1.vWPcBMBGJzvjKsb8.D2EVtw==
  redirect-uri: http://localhost:8080/api/v1/community/linkedin/callback


cloud:
  aws:
    credentials:
      access-key: AKIATH22YZ4Z4EVCPNV2
      secret-key: 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
      region: ap-south-1
    venture:
      images-bucket: cobrother-storage

razorpay:
  key-id: rzp_test_SQN5WUSMW35meT
  key-secret: NcccbwDMc0m3QF9wVGAh0lt0