server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: false
        same-site: lax

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cobrother
    username: postgres
    password: Aultum307
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
